### ISSUE TITLE
Add a run_summary feature to mth5

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mth5#96] opened 2022-04-26 02:37 UTC
The channel_summary is really useful, but I find that when I extract it, I often iterate over the channels, grouping by combinations of station and run, to produce a dataframe with one row per run.

This data structure is handy for deciding what runs (or combinations of runs) to group together for processing, i.e. pass to a TF Kernel.

The run summary would have most of the column names in common with the channel_summary, but could have an additional column that has a list of strings denoting channel names, or maybe a string that maps to one of the common configurations of channels, such as

Cases:
{ ex, ey, hx, hy, hz}
{ ex, ey, hx, hy}
{hx, hy, hz}

I have a sort of prototype in aurora/tf_kernel/dataset.py in a function called 
channel_summary_to_run_summary(), but I am not yet handling channel names grouping, and also maybe should be groupby on (survey, station, run), not (station, run)

**Comment by kujaku11** [comment] 2023-03-29 00:58
Duplicate of #86

**Closed by kujaku11** 2023-03-29 00:58 UTC
Labels: enhancement
